export default {
  developer: require('../assets/images/dev.png'),
  register: require('../assets/images/register.png'),
  Ellipse1: require('../assets/images/Ellipse1.png'),
  Ellipse2: require('../assets/images/Ellipse2.png'),
  welcomeCats: require('../assets/images/welcome_cats.png'),
  star1: require('../assets/images/star1.png'),
  path1: require('../assets/images/path1.png'),
  authentication: require('../assets/images/authentication.png'),
  loginImage: require('../assets/images/login_image.png'),
  forgotPassword: require('../assets/images/forgot_password.png'),
  resetImage: require('../assets/images/reset-image.png'),
  resetPassword: require('../assets/images/reset-password.png'),
  onIcon: require('../assets/images/onIcon.png'),
  onIconWhite: require('../assets/images/onIconWhite.png'),
  server: require('../assets/images/server.png'),
  LOADING: require('../assets/images/loading.json'),
  shieldCheck: require('../assets/images/shieldCheck.png'),
  upload: require('../assets/images/upload.png'),
  download: require('../assets/images/download.png'),
  italy: require('../assets/images/italy.png'),
  ads: require('../assets/images/ads.png'),
  trophy: require('../assets/images/trophy.png'),
  avatar1: require('../assets/images/avatar1.png'),
  dashedCircle: require('../assets/images/dashedCircle.png'),
  
  splash1: require('../assets/images/splash1.png'),
  splash2: require('../assets/images/splash2.png'),
  splash3: require('../assets/images/splash3.png'),

  longRightArrow: require('../assets/images/longRightArrow.png'),
};
